
name: Packer Validate Workflow

on:
  pull_request:
    branches: [ "main" ]

jobs:
  packer:
    name: Packer Validate
    runs-on: ubuntu-latest
    env:
      PKR_VAR_project_id: ${{secrets.PROJECT_ID}}
      PKR_VAR_source_image_family: ${{secrets.SOURCE_IMAGE_FAMILY}}
      PKR_VAR_custom_image_zone: ${{secrets.CUSTOM_IMAGE_ZONE}}
      PKR_VAR_ssh_username: ${{secrets.SSH_USERNAME}}
      PKR_VAR_custom_image_network: ${{secrets.CUSTOM_IMAGE_NETWORK}}
      PKR_VAR_custom_image_name: ${{secrets.CUSTOM_IMAGE_NAME}}
      PKR_VAR_custom_image_description: ${{secrets.CUSTOM_IMAGE_DESCRIPTION}}
      PKR_VAR_service_account_email: ${{secrets.SERVICE_ACCOUNT_EMAIL}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Cloud Platform Credentials
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{secrets.CREDENTIALS_JSON}}'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Log Directory
        run: |
          sudo chmod -R 733 /var/log

      - name: Build with Maven
        run: mvn -B package -DskipTests=true --file pom.xml

      - name: Setup packer
        uses: hashicorp/setup-packer@main

      - name: Packer Init
        working-directory: ./packer
        run: "packer init ."

      - name: Packer Fmt
        working-directory: ./packer
        run: packer fmt -check .

      - name: Packer Validate
        working-directory: ./packer
        run: "packer validate ."